/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.creativeidesign.timekeeper_v1.GUI;
import net.creativeidesign.timekeeper_v1.UserModel;
import net.creativeidesign.timekeeper_v1.util.BigDump;
import net.creativeidesign.timekeeper_v1.util.SyncData;
import net.creativeidesign.timekeeper_v1.util.TaskImport;

/**
 *
 * @author Pi
 */
public class MainDesktopPane extends javax.swing.JFrame {
    
    private UserModel currentUserModel;
    /**
     * Creates new form TimeKeeper_v1_GUI
     */
    public MainDesktopPane(UserModel um) {
        currentUserModel = um;
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem9 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addItemMenuItem = new javax.swing.JMenuItem();
        importMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        syncMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        allTasksMenuBtn = new javax.swing.JMenuItem();
        importantMenuBtn = new javax.swing.JMenuItem();
        importantNotSoonMenuItem = new javax.swing.JMenuItem();
        notImpSoonMenuItem = new javax.swing.JMenuItem();
        notImpNotSoonMenuItem = new javax.swing.JMenuItem();
        finishedTaskMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        compactViewMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Keeper - desktop [v0.2]");

        desktopPane.setName(""); // NOI18N

        menuBar.setName(""); // NOI18N

        jMenu1.setMnemonic('f');
        jMenu1.setText("File");

        addItemMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        addItemMenuItem.setText("Add Item");
        addItemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addItemMenuItem);

        importMenuItem.setText("Import");
        importMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(importMenuItem);

        exportMenuItem.setText("Export");
        exportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exportMenuItem);

        syncMenuItem.setText("Syncronize");
        syncMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syncMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(syncMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        menuBar.add(jMenu1);

        jMenu2.setMnemonic('c');
        jMenu2.setText("Category");

        allTasksMenuBtn.setText("All Tasks");
        allTasksMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTasksMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(allTasksMenuBtn);

        importantMenuBtn.setText("Important [Soon]");
        importantMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importantMenuBtnActionPerformed(evt);
            }
        });
        jMenu2.add(importantMenuBtn);

        importantNotSoonMenuItem.setText("Important [Not Soon]");
        importantNotSoonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importantNotSoonMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(importantNotSoonMenuItem);

        notImpSoonMenuItem.setText("Not Important [Soon]");
        notImpSoonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notImpSoonMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(notImpSoonMenuItem);

        notImpNotSoonMenuItem.setText("Not Important [Not Soon]");
        notImpNotSoonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notImpNotSoonMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(notImpNotSoonMenuItem);

        finishedTaskMenuItem.setText("Finished Tasks");
        finishedTaskMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedTaskMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(finishedTaskMenuItem);

        menuBar.add(jMenu2);

        jMenu3.setMnemonic('w');
        jMenu3.setText("Window");

        jMenuItem12.setText("Start Screen");
        jMenu3.add(jMenuItem12);

        compactViewMenuItem.setText("Compact view");
        compactViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compactViewMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(compactViewMenuItem);

        menuBar.add(jMenu3);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Settings");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        desktopPane.getAccessibleContext().setAccessibleName("mainDesktop");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initMyComponents(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDesktopPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDesktopPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDesktopPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDesktopPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void importMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importMenuItemActionPerformed
        TaskImport ti = new TaskImport();
        if(ti.doImport()){
            CategoryTableView ctv = new CategoryTableView();
            desktopPane.add(ctv);
            ctv.setVisible(true);
        }
    }//GEN-LAST:event_importMenuItemActionPerformed

    private void addItemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemMenuItemActionPerformed
        AddEditItem addItem = new AddEditItem();
        desktopPane.add(addItem);
        addItem.setVisible(true);
    }//GEN-LAST:event_addItemMenuItemActionPerformed

    private void importantMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importantMenuBtnActionPerformed
        CategoryTableView ctv = new CategoryTableView(1);
        desktopPane.add(ctv);
        ctv.setVisible(true);
    }//GEN-LAST:event_importantMenuBtnActionPerformed

    private void allTasksMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTasksMenuBtnActionPerformed
        CategoryTableView ctv = new CategoryTableView();
        desktopPane.add(ctv);
        ctv.setVisible(true);
    }//GEN-LAST:event_allTasksMenuBtnActionPerformed

    private void importantNotSoonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importantNotSoonMenuItemActionPerformed
        CategoryTableView ctv = new CategoryTableView(2);
        desktopPane.add(ctv);
        ctv.setVisible(true);
    }//GEN-LAST:event_importantNotSoonMenuItemActionPerformed

    private void notImpSoonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notImpSoonMenuItemActionPerformed
        CategoryTableView ctv = new CategoryTableView(3);
        desktopPane.add(ctv);
        ctv.setVisible(true);
    }//GEN-LAST:event_notImpSoonMenuItemActionPerformed

    private void notImpNotSoonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notImpNotSoonMenuItemActionPerformed
        CategoryTableView ctv = new CategoryTableView(4);
        desktopPane.add(ctv);
        ctv.setVisible(true);
    }//GEN-LAST:event_notImpNotSoonMenuItemActionPerformed

    private void exportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportMenuItemActionPerformed
        BigDump dump = new BigDump();
        dump.export();
    }//GEN-LAST:event_exportMenuItemActionPerformed

    private void finishedTaskMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedTaskMenuItemActionPerformed
        CategoryTableView ctv = new CategoryTableView(99);
        desktopPane.add(ctv);
        ctv.setVisible(true);
    }//GEN-LAST:event_finishedTaskMenuItemActionPerformed

    private void compactViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compactViewMenuItemActionPerformed
        setVisible(false);
        CompactView cp = new CompactView(this);
        cp.setVisible(true);
    }//GEN-LAST:event_compactViewMenuItemActionPerformed

    private void syncMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncMenuItemActionPerformed
        if(SyncData.upSync()){
            System.out.println("Sysced sucessfully");
        }else
            System.out.println("Something went wrong");
    }//GEN-LAST:event_syncMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem addItemMenuItem;
    private javax.swing.JMenuItem allTasksMenuBtn;
    private javax.swing.JMenuItem compactViewMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenuItem finishedTaskMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JMenuItem importantMenuBtn;
    private javax.swing.JMenuItem importantNotSoonMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem notImpNotSoonMenuItem;
    private javax.swing.JMenuItem notImpSoonMenuItem;
    private javax.swing.JMenuItem syncMenuItem;
    // End of variables declaration//GEN-END:variables

}
